title: OMNeT++ Discrete Event Simulator
author: OMNeT++ Dev Team
email: omnetpp@googlegroups.com

twitter_username: omnetpp
github_username:  omnetpp
excerpt_separator: <!--more-->
google_analytics: UA-240922-2

sass:
    style: compressed

plugins:
    - jekyll-paginate
    - jekyll-redirect-from
